export const navItems  = [
  {
    "type": "link",
    "link": "/",
    "label": "home"
  },
  {
    "type": "dropdown",
    "dropdown": [
      {
        "type": "link",
        "link": "/demo-day",
        "label": "GSoC Demo Day"
      },
      {
        "type": "link",
        "link": "/events",
        "label": "GSoC Alumni Summit"
      },
    ],
    "label": "events"
  },
  {
    "type": "dropdown",
    "dropdown": [
      {
        "type": "link",
        "link": "/events",
        "label": "Open Source AI Club"
      },
    ],
    "label": "meet-ups"
  },
  {
    "type": "dropdown",
    "dropdown": [
      {
        "type": "link",
        "link": "/events",
        "label": "Rocket.Chat Apps Workshop"
      },
      {
        "type": "link",
        "link": "/events",
        "label": "Prompt Engineering Workshop"
      },
    ],
    "label": "workshops"
  },
  {
    "type": "link",
    "link": "/projects",
    "label": "projects"
  },
];

export const speakers = [
  {
      "id": 1,
      "name": "Gabriel Engel",
      "email": "gabriel.engel@rocket.chat",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/gabriel.engel",
      "organisation": "Rocket.Chat",
      "position": "Founder of Rocket.Chat",
      "country": null,
      "short_biography": "Creating the platform for human collaboration over the Internet, powered by the global open source community.",
      "long_biography": "Gabriel Engel is the founder of Rocket.Chat.  Rocket.Chat is the leading open source team collaboration platform that allows users to chat securely on the web, desktop, or mobile; featuring extensive interoperability options with most major open source and commercial messaging platforms.<br/><p>Gabriel founded Rocket.Chat in 2015 and is passionate about open source and emerging technologies that empowers humanity to better collaborate over the Internet. Prior to Rocket.Chat, Gabriel co-founded Konecty, and worked as Product Manager for Business Innovation and Mobile Applications at Vodafone Global Enterprise. Gabriel’s long-term vision for Rocket.Chat is to replace email with a real-time user friendly federated communications platform.",
      "website": "https://github.com/RocketChat/Rocket.Chat",
      "twitter": "https://twitter.com/gabriel_engel",
      "facebook": null,
      "github": "https://github.com/engelgabriel",
      "linkedin": "https://br.linkedin.com/in/gabrielengel",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-07-20T11:58:02.311137+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": false,
      "mastodon": null,
      "modified_at": "2022-07-20 11:58:02.311137+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 2,
      "name": "Rodrigo Nascimento",
      "email": "rodrigo.nascimento@rocket.chat",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/rodrigo.nascimento",
      "organisation": "Rocket.Chat",
      "position": "Co-founder and CTO of Rocket.Chat",
      "country": null,
      "short_biography": "Rocket.Chat architect and technology leader.",
      "long_biography": "Rodrigo co-founded Rocket.Chat in 2015 and is passionate about collaboration tools, programming, open source and new tech. Prior to Rocket.Chat, Rodrigo worked for Konecty as Full-Stack Developer and founded Carddi, a startup aiming to bring the restaurants information close to the people.",
      "website": "https://github.com/RocketChat/Rocket.Chat",
      "twitter": "https://twitter.com/orodrigok",
      "facebook": null,
      "github": "https://github.com/rodrigok",
      "linkedin": "https://br.linkedin.com/in/rodrigoknascimento",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-07-20T11:58:02.311137+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": false,
      "mastodon": null,
      "modified_at": "2022-07-20 11:58:02.311137+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 3,
      "name": "Sing Li",
      "email": "sing.li@rocket.chat",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/sing.li",
      "organisation": "Rocket.Chat",
      "position": "COppO of Rocket.Chat",
      "country": null,
      "short_biography": "Creating the platform for human collaboration over the Internet, powered by the global open source community.",
      "long_biography": "Sing Li is a dynamic leader with a wealth of experience in building and managing communities. As the Chief Opportunities Officer of RocketChat, he is responsible for identifying and seizing new opportunities for growth and expansion. In addition to his role at RocketChat, Sing is also the Community Manager of Google Summer of Code, where he works to connect students with open-source projects and mentors. With his deep understanding of the open-source landscape and his ability to bring people together, Sing is a valuable asset to any team.",
      "website": "https://github.com/RocketChat/Rocket.Chat",
      "twitter": "https://github.com/Sing-Li",
      "facebook": null,
      "github": "https://github.com/Sing-Li",
      "linkedin": "https://www.linkedin.com/in/sing-li-119716139",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-07-20T11:58:02.311137+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": false,
      "mastodon": null,
      "modified_at": "2022-07-20 11:58:02.311137+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 4,
      "name": "Gabriel Casals",
      "email": "gabriel.casals@rocket.chat",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/gabriel.casals",
      "organisation": "RC",
      "position": "Rocket.Chat Senior Engineering Manager",
      "country": null,
      "short_biography": "Senior engineering manager with over 10 years of experience in leading remote teams and delivering innovative solutions.",
      "long_biography": "Gabriel Casals is a Senior Engineering Manager at Rocket.Chat and also a GSoC Administrator who knows how to turn ideas into reality. He has over 10 years of experience in working with projects of different sizes and scopes, both locally and globally, in various domains such as e-commerce, education, health, and finance. He is an expert in agile software development, scrum, and agile management, and has led remote teams using these methodologies. He is also an admirer of topics related to innovation, change management, and business strategy, and has shared his insights and knowledge through workshops and events.",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": "https://github.com/casalsgh",
      "linkedin": "https://br.linkedin.com/in/gabriel-casals-89688328",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-06-27T14:29:11.268921+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": false,
      "is_featured": true,
      "mastodon": null,
      "modified_at": "2022-06-27 19:04:40.019102+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 6,
      "name": "Karan Bedi",
      "email": "akashmalinimurugu@gmail.com",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/karan.bedi",
      "organisation": null,
      "position": "Rocket.Chat GSoC Alumni",
      "country": null,
      "short_biography": "Co-founder at 0xPPL.com",
      "long_biography": "",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": "https://www.linkedin.com/in/kb0304/",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-07-20T11:53:47.436338+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": false,
      "is_featured": false,
      "mastodon": null,
      "modified_at": "2022-07-20 11:53:47.436338+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 7,
      "name": "Shubham Bhardwaj",
      "email": "shubhambhardwajfdb@gmail.com",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/bhardwaj.shubham",
      "organisation": "RC",
      "position": "Rocket.Chat Mentor",
      "country": null,
      "short_biography": "Software Engineer @DressLife (Germany based AI startup)",
      "long_biography": "",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": null,
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-06-28T15:31:09.971650+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": true,
      "mastodon": null,
      "modified_at": "2022-06-30 15:11:51.966253+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 8,
      "name": "Nabhag Motivaras",
      "email": "nabhagmotivaras76@gmail.com",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/nabhag.motivaras",
      "organisation": "RC",
      "position": "Rocket.Chat Mentor",
      "country": null,
      "short_biography": "A Final year Computer Engineering student with a knack for engineering and innovation. I enjoy creating plugins and integrations that makes a difference. I thrive in hackathon environments and have contributed and created notable projects like the Notion App and CoverCraft - Figma plugin to directly Set Cover Image to Hashnode blog post, Currently building OpenStatus Raycast Extension.",
      "long_biography": "Hello everyone! Beyond my academic pursuits, I thrive in hackathon environments, where I am able to channel my passion for designing plugins. My broader focus extends to creating developer tools and products that enhance the overall developer experience. Embracing the world of open source empowers me to work on projects close to my heart. I''ve also had the honor of participating in Google Summer of Code, which has added another layer of enrichment to my journey. Currently, I am focused on building the OpenStatusHQ Raycast Extension, while continuously seeking new challenges and opportunities for growth.",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": null,
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-06-30T15:19:19.762196+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": true,
      "mastodon": null,
      "modified_at": "2022-07-01 09:06:08.843396+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 9,
      "name": "Samad Yar Khan",
      "email": "smdyarkhan123@gmail.com",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/samad.khan",
      "organisation": "RC",
      "position": "Rocket.Chat Mentor",
      "country": null,
      "short_biography": "SDE@Middleware | GSoC''22,23 | Ex-Samsung | OpenSource@RocketChat | NSIT''23",
      "long_biography": "",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": "https://www.linkedin.com/in/samad-yar-khan/",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-06-30T15:16:20.899809+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": true,
      "mastodon": null,
      "modified_at": "2022-07-01 09:07:26.811870+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 10,
      "name": "Shiqi Mei",
      "email": "m1057505415@gmail.com",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/shiqimei",
      "organisation": "RC",
      "position": "Rocket.Chat Mentor",
      "country": null,
      "short_biography": "Currently building an AI startup | Lead the development of a cross-platform rendering framework at KuGou. I have a significant footprint in the open-source community, contributing to various projects (e.g. markboard) and mentoring in Google Summer of Code for years.",
      "long_biography": "",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": "https://www.linkedin.com/in/shiqimei/",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-06-30T15:17:57.147286+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": true,
      "mastodon": null,
      "modified_at": "2022-07-01 09:08:08.534778+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 11,
      "name": "Abhinav Kumar",
      "email": "abhinav.kumar@rocket.chat",
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/abhinav.k",
      "organisation": null,
      "position": "Rocket.Chat Mentor",
      "country": null,
      "short_biography": "Mid Fullstack Engineer @Rocket.Chat | Google SoC ''23 | ❤️ Open Source",
      "long_biography": "",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": "https://www.linkedin.com/in/abhinavkrin",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-07-20T11:58:02.311137+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": false,
      "mastodon": null,
      "modified_at": "2022-07-20 11:58:02.311137+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 12,
      "name": "Murtaza Patrawala",
      "email": null,
      "mobile": null,
      "photo_url": "https://avatars.githubusercontent.com/u/34130764?v=4",
      "organisation": null,
      "position": "Rocket.Chat GSoC Alumni",
      "country": null,
      "short_biography": "Software Engineer at HackerRank | Former Rocket.Chat & Morgan Stanley | GSoC contributor",
      "long_biography": "Meet Murtaza, a software developer and former GSoC student who loves creating customer-focused apps and building solutions. When not coding, Murtaza enjoys traveling and hiking to new places. Join Murtaza for a playful and informative session on GSoC and gain insights from his experience.",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": "https://github.com/murtaza98",
      "linkedin": "https://www.linkedin.com/in/murtaza-p/",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-07-20T11:58:02.311137+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": false,
      "mastodon": null,
      "modified_at": "2022-07-20 11:58:02.311137+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 13,
      "name": "Ezequiel Reis",
      "email": null,
      "mobile": null,
      "photo_url": "https://open.rocket.chat/avatar/ezequiel.reis",
      "organisation": null,
      "position": "Rocket.Chat GSoC Alumni",
      "country": null,
      "short_biography": "Software Engineer at QuintoAndar | Software Developer Engineer (SDE) | Full Stack Developer | Software Analyst | Software Engineer",
      "long_biography": null,
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": "https://www.linkedin.com/in/ezequiel-oliveira/?locale=en_US",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-07-20T11:58:02.311137+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": false,
      "mastodon": null,
      "modified_at": "2022-07-20 11:58:02.311137+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  },
  {
      "id": 14,
      "name": "Devanshu Sharma",
      "email": "devanshu.sharma@rocket.chat",
      "mobile": null,
      "photo_url": "https://media.licdn.com/dms/image/C5603AQETyWoePdmxJw/profile-displayphoto-shrink_400_400/0/1603711644198?e=1717027200&v=beta&t=dSf3jRGVUOn3SVrKZG9819k-3GenGsysXiKhwL3N69U",
      "organisation": "RC",
      "position": "Rocket.Chat Mentor",
      "country": null,
      "short_biography": "Mid Backend Developer @ Rocket.Chat | GSoC Mentor''23 & 24 | GSoC Alumnus''22 | Currently working with interesting stuff related to LLMs",
      "long_biography": "Devanshu is a Mid Backend Developer @ Rocket.Chat, currently exploring and working on LLMs projects and AI moderation capabilites. He is a GSoC Mentor for 2023 and 2024, and a GSoC Alumnus for 2022. He is passionate about open source and loves to contribute to the community. He is also a tech enthusiast and loves to explore new technologies and tools.",
      "website": null,
      "twitter": null,
      "facebook": null,
      "github": null,
      "linkedin": "https://www.linkedin.com/in/shade00/",
      "address": null,
      "city": null,
      "complex_field_values": null,
      "created_at": "2022-06-28T15:31:09.971650+00:00",
      "deleted_at": null,
      "event_id": 1,
      "gender": null,
      "heard_from": null,
      "icon_image_url": null,
      "instagram": null,
      "is_email_overridden": true,
      "is_featured": true,
      "mastodon": null,
      "modified_at": "2022-06-30 15:11:51.966253+00:00",
      "order": 0,
      "small_image_url": null,
      "speaker_positions": {},
      "speaking_experience": null,
      "sponsorship_required": null,
      "thumbnail_image_url": null
  }
]

export const events = [
  {
      "id": "26",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T06:00:00Z",
      "End": "2024-09-01T06:05:00Z",
      "Title": "Welcome to Rocket.Chat GSOC Demo Day 2024!",
      "Mentor": "",
      "Description": "Let's welcome all participants, contributors and Mentor!",
      "Speaker": "Sing Li & Felipe Scuciatto",
      "Duration": 5,
      "Youtube": null
  },
  {
      "id": "27",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T06:05:00Z",
      "End": "2024-09-01T06:20:00Z",
      "Mentor": "Douglas, Devanshu, Sing Li",
      "Title": "AI Newsletter Generator and Publisher",
      "Speaker": "Yuriko Kikuchi",
      "Duration": 15,
      "Youtube": null,
      "Description": "This Rocket.Chat app leverages modern open source LLMs (Mistral, Llama2, Phi, and so on) to help generate newsletters for special interest groups and/or teams operating on a Rocket.Chat server. The newsletter author should be able to supply raw content to the AI generator and have perfectly phrased and formatted newsletter generated. The app should allow for the immediate or scheduled publication of the resulting newsletter to either a team, subset of the server's user, or all of the server's users. The app should also allow for emailing those who prefers to receive the newsletter via email. Ideally the app should maintain a list of dynamically changing newsletter subscribers."
  },
  {
      "id": "28",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T06:20:00Z",
      "End": "2024-09-01T06:35:00Z",
      "Mentor": "Sing Li, Shubham Bhardwaj, John Crisp",
      "Title": "Extended LLM Prompt Editor/Explorer",
      "Duration": 15,
      "Youtube": null,
      "Speaker": "Ashutosh Singh",
      "Description": "The project aims to develop a comprehensive prompt editor within Rocket.Chat, facilitating seamless interaction between users and open source language models (LLMs) such as Mistral, Llama 2, and Phi. Key objectives include enabling free-flowing conversations, robust conversation history management, and seamless prompt sharing across external applications. The initial focus will be on implementing this functionality within the Rocket.Chat Web App and Electron platform."
  },
  {
      "id": "29",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Anjaneya Gupta",
      "Start": "2024-09-01T06:35:00Z",
      "End": "2024-09-01T06:50:00Z",
      "Mentor": "M.PalaniKannan, Sing Li",
      "Title": "GSoC Community Hub 2024",
      "Duration": 15,
      "Youtube": null,
      "Description": "The Ultimate Solution for Scalable Static Websites Full-Stack Functionality: Seamlessly integrate data from the serverless CMS when needed, or choose alternative data sources according to your project requirements. Enhanced Syntax - Tailored for an effortless experience for community creators."
  },
  {
      "id": "30",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T06:50:00Z",
      "End": "2024-09-01T07:05:00Z",
      "Mentor": "Sing Li, Shubham Bhardwaj",
      "Title": "AI Emoji Embellisher",
      "Duration": 15,
      "Speaker": "Sandeep Pillai",
      "Youtube": null,
      "Description": "Text embellishment is a natural language generation problem that aims to enhance the lexical and syntactic complexity of a text while retaining the same semantic information and meaning. This is often achieved by incorporating emojis, punctuation, and additional details to make the text more interesting and engaging. This proposal delves into the implementation details of the Embellisher App for Rocket.Chat. This app will enable users to generate emojified / embellished text messages from plain text messages they enter in the message box using open-source LLMs. Upon generation, the user will be notified with an interactive message that only the sender can see."
  },
  {
      "id": "31",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T07:05:00Z",
      "End": "2024-09-01T07:20:00Z",
      "Mentor": "",
      "Title": "15 minutes Break",
      "Description": "",
      "Duration": 15,
      "Youtube": null
  },
  {
      "id": "32",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Abhi Patel",
      "Start": "2024-09-01T07:20:00Z",
      "End": "2024-09-01T07:35:00Z",
      "Mentor": "Dhruv Jain, Rodrigo Nascimento",
      "Title": "Multiple file sharing in one message",
      "Duration": 15,
      "Youtube": null,
      "Description": "My project enhances file sharing functionality by allowing users to send multiple files in a single message, a significant improvement over the previous limitation of sharing only one file at a time. Users can easily add files they may have forgotten to include, and they can also remove files that were mistakenly selected."
  },
  {
      "id": "33",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Akshun Kuthiala",
      "Start": "2024-09-01T07:35:00Z",
      "End": "2024-09-01T07:50:00Z",
      "Mentor": "Guilherme Gazzo, Diego Sampaio, Rodrigo Nascimento",
      "Title": "API Documentation Generator",
      "Duration": 15,
      "Youtube": null,
      "Description": "API documentation plays a vital role in developers\u2019 workflow, serving as an essential reference for software integration and development. However, challenges such as outdated or inconsistent documentation frequently hinder efficient utilization. To address this, the proposed project aims to implement automation for API documentation generation leveraging a suite of tools including API Extractor, Typescript, Swagger and OpenAPI specifications. This initiative seeks to streamline the documentation process, ensuring accuracy, consistency, and timeliness in API references, thus enhancing overall development productivity and efficacy."
  },
  {
      "id": "34",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Aman Negi",
      "Start": "2024-09-01T07:50:00Z",
      "End": "2024-09-01T08:05:00Z",
      "Mentor": "Nabhag Motivaras",
      "Title": "AI in-channel GIF Image Generator",
      "Duration": 15,
      "Youtube": null,
      "Description": "Imagine expressing yourself with GIFs that perfectly capture your ideas and emotions, all within the familiar Rocket.Chat interface. This innovative app takes GIF creation beyond simply searching for existing ones. It empowers you to generate entirely new GIFs based on your descriptive prompts! Here's what makes this app truly stand out: - Prompt-based Generation: Simply describe what you want the GIF to show, and the app uses an open-source text-to-GIF model to bring your vision to life! You can even easily integrate your own model for even more customization. - Seamless Workflow: Generated GIFs are readily available for use anywhere within Rocket.Chat. No need to switch applications or upload files \u2013 it's all integrated into your chat flow. - Don't Settle for the First Try: Not quite happy with the generated GIF? Simply regenerate it with a click for a better match to your needs. - Enhanced with NLP: Can't think of a perfect prompt? Use the prompt generation feature which uses LLM as NLP, leading to even better GIF generation results. - Profanity Filter: Maintain a professional environment with the NSFW content filtering feature, ensuring appropriate content creation. - Extensive History Management: This app goes beyond just storing the last ten creations which is standard for most RC Apps. Pagination allows you to view and access a much larger history of generated GIFs. This app, with its level of customization, built-in NLP features, and user-friendly design, becomes a powerful tool for anyone who wants to express themselves visually within their Rocket.Chat chats. It injects a whole new level of creativity and fun into your communication, making it a truly valuable addition to the platform."
  },
  {
      "id": "35",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Hardik Bhatia",
      "Start": "2024-09-01T08:05:00Z",
      "End": "2024-09-01T08:20:00Z",
      "Mentor": "Gabriel Casals, Felipe Scuciatto",
      "Title": "AgileBot",
      "Duration": 15,
      "Youtube": null,
      "Description": "This project aims to enhance team productivity within agile environments by using a chatbot-based approach. By developing a chatbot that is customized to meet the needs of agile workflows, teams will be able to streamline communication, task management, and meeting coordination. This project will be implemented via the apps engine in Rocket.chat."
  },
  {
      "id": "36",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T08:20:00Z",
      "End": "2024-09-01T08:35:00Z",
      "Mentor": "",
      "Title": "15 minutes Break",
      "Description": "",
      "Duration": 15,
      "Youtube": null
  },
  {
      "id": "37",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Hunter Xia",
      "Start": "2024-09-01T08:35:00Z",
      "End": "2024-09-01T08:50:00Z",
      "Mentor": "Shiqi Mei",
      "Title": "AI Query Bot",
      "Duration": 15,
      "Youtube": null,
      "Description": "The AI Query Bot project is a cutting-edge Rocket.Chat application designed to revolutionize information retrieval by leveraging a highly configurable Retrieval Augmented Generation (RAG) pipeline. This pipeline integrates advanced natural language processing (NLP) technologies to deliver precise and contextually relevant answers to user queries. Users can customize various components, including embedding/tokenizer engines, vector database search algorithms, re-ranking strategies, and the choice of open-source Large Language Models (LLMs) like Mistral, Llama, and Phi. This flexibility ensures the bot can be tailored to meet specific needs and domains effectively."
  },
  {
      "id": "38",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Jeffrey Yu",
      "Start": "2024-09-01T08:50:00Z",
      "End": "2024-09-01T09:05:00Z",
      "Mentor": "Devanshu Sharma, Sing Li",
      "Title": "Rocket.Chat AI Chat Summarizer",
      "Duration": 15,
      "Youtube": null,
      "Description": "This project aims to deliver a Rocket.Chat App that uses generative AI to summarize any conversations across threads, channels, and DMs. For example, a user can say, 'summarize my unread messages yesterday in the #engineering channel'. The users can ask AI any questions regarding the messages, and subscribe to personal digests that summarize selected channels on a recurring schedule. The AI summarizer will boost the productivity of Rocket.Chat users with faster information digest, and improve community engagement by keeping everyone on the same page."
  },
  {
      "id": "39",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Maria Khelli",
      "Start": "2024-09-01T09:05:00Z",
      "End": "2024-09-01T09:20:00Z",
      "Mentor": "Sing Li, Douglas Gubert, Devanshu Sharma",
      "Title": "Smart Scheduling App Assistant",
      "Duration": 15,
      "Youtube": null,
      "Description": "Setting a calendar event is a small, but important process in our day-to-day job. It can take some of your time when you want to set up another meeting if you 1) Already have a tight schedule; 2) Your coworkers are in different time zones; and 3) Have to switch back and forth between the calendar and the messaging app. Hence, this project aims to streamline the process using a scheduling assistant, that can create meetings or set up a reminder using a prompt. The solution will involve a lot of large language models (LLM) experiments for the user prompt. Therefore, this project can act as a semi-research in which the result of LLM experiments can be used to approach similar cases."
  },
  {
      "id": "40",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Prisha Gupta",
      "Start": "2024-09-01T09:20:00Z",
      "End": "2024-09-01T09:35:00Z",
      "Mentor": "Vinayak Sharma",
      "Title": "Ai assistant for rocket chat main repository",
      "Duration": 15,
      "Youtube": null,
      "Description": "An Al-Assistant is developed to help developers understand the Rocket.Chat codebase better. This tool uses the existing knowledge base of the code to answer questions about the code structure and logic. It can answer specific questions about the code, create diagrams to explain things clearer, find relevant documentation, and even suggest ways to improve the code. This will help new developers learn the code faster and make the codebase overall better quality, easier to maintain, and more consistent."
  },
  {
      "id": "41",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Ryan Zhou",
      "Start": "2024-09-01T09:35:00Z",
      "End": "2024-09-01T09:50:00Z",
      "Mentor": "Samad, John, Mustafa",
      "Title": "AI Programmer",
      "Duration": 15,
      "Youtube": null,
      "Description": "This is an AI bot to help you automatically generate code pieces. A Rocket.Chat app that enables the AI programmer functionalities where users can utilize the tool to create a short piece of code in C/C++, Java, Javascript, Typescript or Python based on specification supplied by the user. This implementation includes modern open source LLMs (Mistral, CodeLlama, WizardCode, Llama2, Phi, and so on) for a simplified configuration. This functionality also allows users to ask for a new variation of the code or augment/fine-tune the system for a more precise code generation. To achieve this, we propose to design a more intuitive and interactive UX to simplify users\u2019 interaction. Finally, we will explore to bridge the generated codes with sharing APIs, allowing them to be shared to external applications and added to GitHub as a pull request. The AI Programmer app will be published on Rocket.Chat Marketplace together with specified documentation."
  },
  {
      "id": "42",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T09:50:00Z",
      "End": "2024-09-01T10:05:00Z",
      "Mentor": "",
      "Title": "15 minutes Break",
      "Description": "",
      "Duration": 15,
      "Youtube": null
  },
  {
      "id": "43",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Umang Utkarsh",
      "Start": "2024-09-01T10:05:00Z",
      "End": "2024-09-01T10:20:00Z",
      "Mentor": "Abhinav Kumar",
      "Title": "News Aggregation App",
      "Duration": 15,
      "Youtube": null,
      "Description": "The News Aggregation Rocket.Chat App is designed to deliver the latest news from various sources directly within the Rocket.Chat platform. This project aims to create an application that aggregates news from top websites like TechCrunch and BBC News, utilizing APIs or RSS feeds to collect data. The app will present news in a user-friendly format with complete configurability of sources and categories, ensuring users can customize their news feed according to their preferences. The project will implement logic to collect news, categorize it, and present it effectively within the platform. By enhancing the Rocket.Chat ecosystem, this app aims to offer users a seamless way to stay updated with curated news content without leaving the chat environment."
  },
  {
      "id": "44",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Vipin Chaudhary",
      "Start": "2024-09-01T10:20:00Z",
      "End": "2024-09-01T10:35:00Z",
      "Mentor": "Hugo Costa, Gabriel Casals",
      "Title": "Quick Replies",
      "Duration": 15,
      "Youtube": null,
      "Description": "Quick replies offers a convenient way to send standard responses swiftly, that can work as a pre-written message. Users can effortlessly create, edit, delete, and save a list of these quick replies, leveraging AI to generate responses tailored to their needs."
  },
  {
      "id": "45",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T10:35:00Z",
      "End": "2024-09-01T10:50:00Z",
      "Mentor": "Sidharth Mohanty",
      "Speaker": "Zishan Ahmad",
      "Title": "EmbeddedChat",
      "Duration": 15,
      "Youtube": null,
      "Description": "EmbeddedChat integrates a full-featured chat interface into your app, connected to the Rocket.Chat server, offering easy setup and cool features, including: 1. Flexible Configuration: Adjust the chat window\u2019s size, appearance, and functionality. 2. Extensible Design: Customize the chat\u2019s look with theming options to match your app\u2019s branding. 3. Robust Authentication: Supports various login methods and secure cookie options for auto-login. 4. Real-Time Layout Editing: The \u2018layout-editor\u2019 tool allows users to design and customize EmbeddedChat layouts in real-time using drag-and-drop functionality. It also generates a theme object for easy setup."
  },
  {
      "id": "46",
      "Event": "GSoC Demo Day 2024",
      "Speaker": "Sayan Banerjee",
      "Start": "2024-09-01T10:50:00Z",
      "End": "2024-09-01T11:05:00Z",
      "Mentor": "Aditya Singh",
      "Title": "Graphical Guided RC Code Tours",
      "Duration": 15,
      "Youtube": null,
      "Description": "This project aims to smoothen out the on-boarding process of new contributors to Rocket.Chat. The huge size of Rocket.chat's codebase makes it a overwhelming task to understand and start contributing to it. We use the power of VsCode and its extension CodeTour to explain the most crucial parts of the codebase, motivating them to work towards Open-Source community. We also have circumvented one of the limitations of the Codetour extension, which is its incompatibility with ever-evolving codebases, by employing innovative methods."
  },
  {
      "id": "47",
      "Event": "GSoC Demo Day 2024",
      "Start": "2024-09-01T11:05:00Z",
      "End": "2024-09-01T11:20:00Z",
      "Mentor": "",
      "Title": "Closing Notes",
      "Description": "",
      "Duration": 15,
      "Youtube": null
  }
]